import type { CrmModule } from "../../components/crmTypes";

const crmSalesModules: CrmModule[] = [
  {
    id: "leads",
    title: "Leads",
    group: "Sales",
    endpoint: "leads",
    description:
      "Capture B2C, B2B, corporate, campaign, phone, WhatsApp, referral, and website enquiries.",
    columns: ["Customer", "Destination", "Source", "Stage", "Owner", "Phone"],
    rowMap: [
      "customerName",
      "requirement.destination",
      "source",
      "stage",
      "assignedTo",
      "phone",
    ],
    stageEndpoint: true,
    statusOptions: [
      "new",
      "assigned",
      "contacted",
      "requirement_collected",
      "quotation_prepared",
      "quotation_sent",
      "negotiation",
      "won",
      "lost",
    ],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      {
        key: "source",
        label: "Source",
        required: true,
        placeholder: "Website, WhatsApp, Agent",
      },
      {
        key: "channel",
        label: "Channel",
        type: "select",
        options: [
          { value: "b2c", label: "B2C Customer" },
          { value: "b2b", label: "B2B Agent" },
          { value: "corporate", label: "Corporate Client" },
        ],
      },
      { key: "requirement.destination", label: "Destination" },
      { key: "requirement.travelDate", label: "Travel Date", type: "date" },
      { key: "requirement.adults", label: "Adults", type: "number" },
      { key: "assignedTo", label: "Owner" },
    ],
  },
  {
    id: "customers",
    title: "Customers",
    group: "Sales",
    endpoint: "customers",
    description:
      "Customer master for B2C travellers, repeat customers, families, and corporate contacts.",
    columns: ["Customer", "Phone", "Email", "Type", "City", "Status"],
    rowMap: ["name", "phone", "email", "customerType", "city", "status"],
    statusOptions: ["active", "inactive", "blocked"],
    fields: [
      { key: "name", label: "Customer", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      {
        key: "customerType",
        label: "Type",
        type: "select",
        options: [
          { value: "b2c", label: "B2C Traveller" },
          { value: "b2b", label: "B2B Agent" },
          { value: "corporate", label: "Corporate Account" },
          { value: "family", label: "Family Traveller" },
          { value: "repeat", label: "Repeat Customer" },
        ],
      },
      { key: "source", label: "Source" },
      { key: "city", label: "City" },
      { key: "country", label: "Country" },
    ],
  },
  {
    id: "quotations",
    title: "Quotations",
    group: "Sales",
    endpoint: "quotations",
    description:
      "Build customer pricing with travel dates, travellers, service costs, markup, discount, and status tracking.",
    columns: [
      "Customer",
      "Destination",
      "Travel Dates",
      "Travellers",
      "Total",
      "Status",
    ],
    rowMap: [
      "customerName",
      "destination",
      "travelDates",
      "travellers",
      "sellingPrice",
      "status",
    ],
    statusOptions: ["draft", "sent", "accepted", "rejected", "expired"],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "destination", label: "Destination", required: true },
      { key: "travelDates", label: "Travel Dates" },
      { key: "travellers", label: "Travellers", type: "number" },
      { key: "pricing.baseCost", label: "Base Cost", type: "number" },
      { key: "pricing.markup", label: "Markup", type: "number" },
      { key: "pricing.discount", label: "Discount", type: "number" },
    ],
  },
  {
    id: "itineraries",
    title: "Itineraries",
    group: "Sales",
    endpoint: "itineraries",
    description:
      "Create and maintain day-wise travel plans, templates, themes, and customer-ready itinerary content.",
    columns: ["Itinerary", "Destination", "Days", "Theme", "Status"],
    rowMap: ["title", "destination", "durationDays", "theme", "status"],
    statusOptions: ["draft", "ready", "shared", "archived"],
    fields: [
      { key: "title", label: "Itinerary", required: true },
      { key: "destination", label: "Destination", required: true },
      { key: "durationDays", label: "Days", type: "number" },
      { key: "theme", label: "Theme" },
    ],
  },
  {
    id: "bookings",
    title: "Bookings",
    group: "Operations",
    endpoint: "bookings",
    description:
      "Confirmed travel files with passengers, services, documents, payments, vouchers, and trip status.",
    columns: [
      "Customer",
      "Destination",
      "Travel Dates",
      "Passengers",
      "Services",
      "Status",
    ],
    rowMap: [
      "customerName",
      "destination",
      "travelDates",
      "passengers",
      "services",
      "status",
    ],
    statusOptions: [
      "draft",
      "pending_payment",
      "confirmed",
      "partially_confirmed",
      "cancelled",
      "completed",
    ],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "destination", label: "Destination", required: true },
      { key: "travelDates", label: "Travel Dates" },
      { key: "quotationId", label: "Quotation ID" },
      { key: "leadId", label: "Lead ID" },
    ],
  },
];

export default crmSalesModules;
