import type { CrmModule } from "../../components/crmTypes";

const ownerFields = [
      { key: "ownerId", label: "Owner User Ref" },
      { key: "teamId", label: "Team Ref" },
      { key: "departmentId", label: "Department Ref" },
];

const crmMetadataFields = [
  { key: "tags", label: "Tags", type: "tags" as const },
  { key: "customFields", label: "Custom Fields", type: "textarea" as const },
  { key: "metadata", label: "Internal Metadata", type: "textarea" as const },
];

const crmSalesModules: CrmModule[] = [
  {
    id: "leads",
    title: "Leads",
    group: "Sales",
    endpoint: "leads",
    description:
      "Capture B2C, B2B, corporate, campaign, phone, WhatsApp, referral, and website enquiries.",
    columns: [
      "Customer",
      "Destination",
      "Source",
      "Stage",
      "Owner",
      "Next Follow-up",
      "Phone",
    ],
    rowMap: [
      "customerName",
      "requirement.destination",
      "source",
      "stage",
      "ownerId",
      "nextFollowUpAt",
      "phone",
    ],
    stageEndpoint: true,
    statusOptions: [
      "new",
      "assigned",
      "contacted",
      "requirement_collected",
      "quotation_prepared",
      "quotation_sent",
      "negotiation",
      "won",
      "lost",
    ],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      {
        key: "source",
        label: "Source",
        required: true,
        placeholder: "Website, WhatsApp, Agent",
      },
      {
        key: "channel",
        label: "Channel",
        type: "select",
        options: [
          { value: "b2c", label: "B2C Customer" },
          { value: "b2b", label: "B2B Agent" },
          { value: "corporate", label: "Corporate Client" },
        ],
      },
      { key: "requirement.destination", label: "Destination" },
      { key: "requirement.travelDate", label: "Travel Date", type: "date" },
      { key: "requirement.adults", label: "Adults", type: "number" },
      { key: "assignedTo", label: "Owner" },
      ...ownerFields,
      { key: "externalReference", label: "External Reference" },
      { key: "nextFollowUpAt", label: "Next Follow-up", type: "date" },
      { key: "consent", label: "Consent Details", type: "textarea" },
      ...crmMetadataFields,
    ],
  },
  {
    id: "customers",
    title: "Customers",
    group: "Sales",
    endpoint: "customers",
    description:
      "Customer master for B2C travellers, repeat customers, families, and corporate contacts.",
    columns: ["Customer", "Phone", "Email", "Type", "Owner", "Tags", "Status"],
    rowMap: ["name", "phone", "email", "customerType", "ownerId", "tags", "status"],
    statusOptions: ["active", "inactive", "blocked"],
    fields: [
      { key: "name", label: "Customer", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      {
        key: "customerType",
        label: "Type",
        type: "select",
        options: [
          { value: "b2c", label: "B2C Traveller" },
          { value: "b2b", label: "B2B Agent" },
          { value: "corporate", label: "Corporate Account" },
          { value: "family", label: "Family Traveller" },
          { value: "repeat", label: "Repeat Customer" },
        ],
      },
      { key: "source", label: "Source" },
      { key: "city", label: "City" },
      { key: "country", label: "Country" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "externalReference", label: "External Reference" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "preferences", label: "Travel Preferences", type: "textarea" },
      { key: "consent", label: "Consent Details", type: "textarea" },
      { key: "loyalty", label: "Loyalty Details", type: "textarea" },
      { key: "customFields", label: "Custom Fields", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "quotations",
    title: "Quotations",
    group: "Sales",
    endpoint: "quotations",
    description:
      "Build customer pricing with travel dates, travellers, service costs, markup, discount, and status tracking.",
    columns: [
      "Quote No",
      "Customer",
      "Destination",
      "Travel Dates",
      "Travellers",
      "Total",
      "Status",
    ],
    rowMap: [
      "quoteNo",
      "customerName",
      "destination",
      "travelDates",
      "travellers",
      "sellingPrice",
      "status",
    ],
    statusOptions: ["draft", "sent", "negotiation", "accepted", "rejected"],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "quoteNo", label: "Quote No" },
      { key: "customerId", label: "Customer ID" },
      { key: "leadId", label: "Lead ID" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "agentId", label: "Agent ID" },
      { key: "destination", label: "Destination", required: true },
      { key: "travelDates", label: "Travel Dates" },
      { key: "travellers", label: "Travellers", type: "number" },
      { key: "pricing.baseCost", label: "Base Cost", type: "number" },
      { key: "pricing.markup", label: "Markup", type: "number" },
      { key: "pricing.discount", label: "Discount", type: "number" },
      { key: "validUntil", label: "Valid Until", type: "date" },
      { key: "terms", label: "Terms", type: "textarea" },
      { key: "approval", label: "Approval Details", type: "textarea" },
      ...crmMetadataFields,
    ],
  },
  {
    id: "itineraries",
    title: "Itineraries",
    group: "Sales",
    endpoint: "itineraries",
    description:
      "Create and maintain day-wise travel plans, templates, themes, and customer-ready itinerary content.",
    columns: ["Itinerary", "Destination", "Owner", "Version", "Tags", "Status"],
    rowMap: ["title", "destination", "ownerId", "version", "tags", "status"],
    statusOptions: ["draft", "published", "archived"],
    fields: [
      { key: "title", label: "Itinerary", required: true },
      { key: "quotationId", label: "Quotation ID" },
      { key: "bookingId", label: "Booking ID" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "version", label: "Version", type: "number" },
      { key: "destination", label: "Destination", required: true },
      { key: "days", label: "Day Plan", type: "textarea" },
      { key: "inclusions", label: "Inclusions", type: "textarea" },
      { key: "exclusions", label: "Exclusions", type: "textarea" },
      { key: "travellerNotes", label: "Traveller Notes", type: "textarea" },
      ...crmMetadataFields,
    ],
  },
  {
    id: "bookings",
    title: "Bookings",
    group: "Operations",
    endpoint: "bookings",
    description:
      "Confirmed travel files with passengers, services, documents, payments, vouchers, and trip status.",
    columns: [
      "Booking No",
      "Customer",
      "Destination",
      "Travel Dates",
      "Owner",
      "Agent",
      "Status",
    ],
    rowMap: [
      "bookingNo",
      "customerName",
      "destination",
      "travelDates",
      "ownerId",
      "agentId",
      "status",
    ],
    statusOptions: [
      "draft",
      "pending_payment",
      "confirmed",
      "partially_confirmed",
      "cancelled",
      "completed",
    ],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "bookingNo", label: "Booking No" },
      { key: "customerId", label: "Customer ID" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "agentId", label: "Agent ID" },
      { key: "destination", label: "Destination", required: true },
      { key: "travelDates", label: "Travel Dates" },
      { key: "quotationId", label: "Quotation ID" },
      { key: "leadId", label: "Lead ID" },
      { key: "passengers", label: "Passengers", type: "textarea" },
      { key: "services", label: "Services", type: "textarea" },
      { key: "commercial", label: "Commercials", type: "textarea" },
      { key: "supplierCosting", label: "Supplier Costing", type: "textarea" },
      { key: "cancellationPolicy", label: "Cancellation Policy", type: "textarea" },
      ...crmMetadataFields,
    ],
  },
];

export default crmSalesModules;
