import type { CrmModule } from "../../components/crmTypes";

const financeModules: CrmModule[] = [
  {
    id: "payments",
    title: "Payments",
    group: "Finance",
    endpoint: "payments",
    description:
      "Receivables, payables, agent collections, supplier dues, refunds, due dates, and payment status.",
    columns: ["Payment No", "Type", "Party", "Amount", "Mode", "Reference", "Status"],
    rowMap: [
      "paymentNo",
      "type",
      "partyName",
      "amount",
      "paymentMode",
      "gatewayReference",
      "status",
    ],
    statusOptions: ["pending", "partially_paid", "paid", "overdue", "cancelled"],
    fields: [
      {
        key: "type",
        label: "Type",
        required: true,
        type: "select",
        options: ["receivable", "payable", "refund", "commission"],
      },
      { key: "partyName", label: "Party" },
      { key: "amount", label: "Amount", required: true, type: "number" },
      { key: "amountMinor", label: "Amount Minor", type: "number" },
      { key: "currencyCode", label: "Currency" },
      { key: "paymentNo", label: "Payment No" },
      { key: "bookingId", label: "Booking Ref" },
      { key: "invoiceId", label: "Invoice Ref" },
      { key: "agentId", label: "Agent Ref" },
      { key: "supplierId", label: "Supplier Ref" },
      { key: "dueDate", label: "Due Date", type: "date" },
      { key: "paidAt", label: "Paid At", type: "date" },
      { key: "paymentMode", label: "Payment Mode" },
      { key: "gatewayProvider", label: "Gateway Provider" },
      { key: "gatewayReference", label: "Gateway Reference" },
      { key: "bankReference", label: "Bank Reference" },
      { key: "reconciliation", label: "Reconciliation", type: "textarea" },
      { key: "taxBreakup", label: "Tax Breakup", type: "textarea" },
    ],
  },
  {
    id: "invoices",
    title: "Invoice Builder",
    group: "Finance",
    endpoint: "finance/invoices",
    description:
      "Country-aware invoice utility with provider, customer, tax rules, dynamic line items, and API persistence.",
    columns: ["Invoice", "Customer", "Booking", "Due", "Tax", "Total", "Status"],
    rowMap: [
      "invoiceNo",
      "customer.companyName",
      "bookingId",
      "dueDate",
      "taxLabel",
      "totalPayable",
      "status",
    ],
    fields: [
      { key: "invoiceSeries", label: "Invoice Series", required: true },
      { key: "invoiceNo", label: "Invoice No", required: true },
      { key: "invoiceDate", label: "Invoice Date", required: true, type: "date" },
      { key: "dueDate", label: "Due Date", type: "date" },
      { key: "customerId", label: "Customer ID" },
      { key: "bookingId", label: "Booking ID" },
      { key: "quotationId", label: "Quotation ID" },
      { key: "countryCode", label: "Country Code" },
      { key: "currencyCode", label: "Currency Code" },
      { key: "currencySymbol", label: "Currency Symbol" },
      { key: "taxLabel", label: "Tax Label" },
      { key: "taxRate", label: "Tax Rate", type: "number" },
      { key: "provider", label: "Provider", type: "textarea" },
      { key: "customer", label: "Customer", type: "textarea" },
      { key: "entries", label: "Entries", type: "textarea" },
      { key: "paymentTerms", label: "Payment Terms", type: "textarea" },
      { key: "eInvoice", label: "E-Invoice", type: "textarea" },
      { key: "exportDetails", label: "Export Details", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "finance-reports",
    title: "Finance Reports",
    group: "Finance",
    endpoint: "reporting/finance",
    description:
      "Organization-scoped finance totals across receivables, payables, refunds, commissions, and total movement.",
    columns: ["Metric", "Value"],
    rowMap: ["key", "value"],
    fields: [],
  },
  {
    id: "sales-reports",
    title: "Sales Reports",
    group: "Reports",
    endpoint: "reporting/sales-funnel",
    description:
      "Lead, quotation, and booking funnel summaries grouped by status and stage.",
    columns: ["Metric", "Value"],
    rowMap: ["key", "value"],
    fields: [],
  },
  {
    id: "operations-reports",
    title: "Operations Reports",
    group: "Reports",
    endpoint: "reporting/operations",
    description:
      "Operations task workload grouped by status and priority for branch managers.",
    columns: ["Metric", "Value"],
    rowMap: ["key", "value"],
    fields: [],
  },
  {
    id: "saved-reports",
    title: "Saved Reports",
    group: "Reports",
    endpoint: "saved-reports",
    description:
      "Reusable scheduled report templates for overview, sales funnel, operations, and finance reporting.",
    columns: ["Report", "Type", "Schedule", "Recipients", "Status", "Last Run"],
    rowMap: [
      "name",
      "reportType",
      "schedule",
      "recipients",
      "status",
      "lastRunAt",
    ],
    statusOptions: ["active", "paused", "archived"],
    fields: [
      { key: "name", label: "Report Name", required: true },
      { key: "ownerId", label: "Owner User ID" },
      {
        key: "reportType",
        label: "Report Type",
        required: true,
        type: "select",
        options: ["overview", "sales-funnel", "operations", "finance"],
      },
      { key: "recipients", label: "Recipients", type: "tags" },
      { key: "delivery", label: "Delivery", type: "textarea" },
      { key: "permissions", label: "Permissions", type: "textarea" },
    ],
  },
];

export default financeModules;
