import type { CrmModule } from "../../components/crmTypes";

const identityModules: CrmModule[] = [
  {
    id: "branches",
    title: "Branches",
    group: "Access Control",
    endpoint: "identity/branches",
    description:
      "Organization branch offices, service desks, local settings, and operating status.",
    columns: ["Branch", "Code", "City", "Country", "Timezone", "Status"],
    rowMap: ["name", "code", "city", "country", "timezone", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Branch", required: true },
      { key: "code", label: "Code", required: true },
      { key: "city", label: "City" },
      { key: "country", label: "Country" },
      { key: "timezone", label: "Timezone" },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      { key: "address", label: "Address" },
      { key: "operatingHours", label: "Operating Hours", type: "textarea" },
      { key: "taxProfile", label: "Tax Profile", type: "textarea" },
      { key: "settings", label: "Settings", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "departments",
    title: "Departments",
    group: "Access Control",
    endpoint: "identity/departments",
    description:
      "Branch-level departments for sales, operations, finance, support, and management teams.",
    columns: ["Department", "Code", "Branch", "Manager", "Status"],
    rowMap: ["name", "code", "branchId", "managerUserId", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Department", required: true },
      { key: "code", label: "Code", required: true },
      { key: "branchId", label: "Branch", required: true },
      { key: "managerUserId", label: "Manager User ID" },
      { key: "slaPolicy", label: "SLA Policy", type: "textarea" },
      { key: "settings", label: "Settings", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "teams",
    title: "Teams",
    group: "Access Control",
    endpoint: "identity/teams",
    description:
      "Operational teams with branch, department, team lead, and member assignments.",
    columns: ["Team", "Code", "Branch", "Department", "Lead", "Status"],
    rowMap: [
      "name",
      "code",
      "branchId",
      "departmentId",
      "leadUserId",
      "status",
    ],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Team", required: true },
      { key: "code", label: "Code", required: true },
      { key: "branchId", label: "Branch", required: true },
      { key: "departmentId", label: "Department ID", required: true },
      { key: "leadUserId", label: "Lead User ID" },
      { key: "memberUserIds", label: "Member User IDs", type: "tags" },
      { key: "queueRules", label: "Queue Rules", type: "textarea" },
      { key: "settings", label: "Settings", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "roles",
    title: "Roles",
    group: "Access Control",
    endpoint: "identity/roles",
    description:
      "Organization roles for admins, branch managers, sales, operations, finance, agents, and custom teams.",
    columns: ["Role", "Code", "Type", "Branches", "Status"],
    rowMap: ["name", "code", "roleType", "defaultBranchIds", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Role", required: true },
      { key: "code", label: "Code", required: true },
      {
        key: "roleType",
        label: "Type",
        type: "select",
        options: [
          { value: "system", label: "System" },
          { value: "custom", label: "Custom" },
        ],
      },
      { key: "description", label: "Description" },
      { key: "defaultBranchIds", label: "Default Branch IDs", type: "tags" },
      { key: "defaultDepartmentIds", label: "Default Department IDs", type: "tags" },
      { key: "defaultTeamIds", label: "Default Team IDs", type: "tags" },
      { key: "limits", label: "Limits", type: "textarea" },
    ],
  },
  {
    id: "permissions",
    title: "Permission Registry",
    group: "Access Control",
    endpoint: "identity/permissions",
    description:
      "Platform-managed action permissions used when granting access to organization roles.",
    columns: ["Module", "Action", "Code", "Label", "Status"],
    rowMap: ["module", "action", "code", "label", "status"],
    statusOptions: ["active", "inactive"],
    fields: [],
  },
  {
    id: "user-roles",
    title: "Role Assignments",
    group: "Access Control",
    endpoint: "identity/user-roles",
    description:
      "Assign CRM users to roles and restrict access to selected branches, departments, and teams.",
    columns: ["User", "Role", "Branches", "Departments", "Teams", "Status"],
    rowMap: [
      "userId",
      "roleId",
      "branchIds",
      "departmentIds",
      "teamIds",
      "status",
    ],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "userId", label: "CRM User Ref", required: true },
      { key: "roleId", label: "Role Ref", required: true },
      { key: "branchIds", label: "Allowed Branch Refs", type: "tags" },
      { key: "departmentIds", label: "Allowed Department Refs", type: "tags" },
      { key: "teamIds", label: "Allowed Team Refs", type: "tags" },
    ],
  },
  {
    id: "role-permissions",
    title: "Permission Grants",
    group: "Access Control",
    endpoint: "identity/role-permissions",
    description:
      "Grant module/action permissions to roles with optional scope and conditions.",
    columns: ["Role", "Permission", "Scope", "Status"],
    rowMap: ["roleId", "permissionCode", "scope", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "roleId", label: "Role Ref", required: true },
      { key: "permissionCode", label: "Permission Code", required: true },
      { key: "scope", label: "Scope" },
      { key: "conditions", label: "Conditions", type: "textarea" },
    ],
  },
  {
    id: "invitations",
    title: "Invitations",
    group: "Access Control",
    endpoint: "identity/invitations",
    createEndpoint: "auth/invitations",
    description:
      "Pending, accepted, expired, and revoked user invitations with branch and role context.",
    columns: ["Name", "Email", "Role", "Branch", "Expires", "Status"],
    rowMap: ["name", "email", "role", "branchId", "expiresAt", "status"],
    statusOptions: ["pending", "accepted", "expired", "revoked"],
    fields: [
      { key: "email", label: "Email", required: true, type: "email" },
      { key: "name", label: "Name", required: true },
      { key: "role", label: "Role" },
      { key: "branchId", label: "Branch" },
      { key: "branchIds", label: "Branch IDs", type: "tags" },
      { key: "departmentIds", label: "Department IDs", type: "tags" },
      { key: "teamIds", label: "Team IDs", type: "tags" },
      { key: "permissions", label: "Permissions", type: "tags" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "team-users",
    title: "Users",
    group: "Access Control",
    endpoint: "auth/users",
    createEndpoint: "auth/register-crm-user",
    description:
      "CRM users allowed to access the admin portal. Role policies and branch access are managed through assignments and grants.",
    columns: ["Name", "Email", "Role", "Primary Branch", "Status"],
    rowMap: ["name", "email", "role", "branchId", "status"],
    statusOptions: ["active", "inactive", "locked", "invited"],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "email", label: "Email", required: true, type: "email" },
      { key: "password", label: "Temporary Password", required: true },
      { key: "role", label: "Primary Role Code" },
      { key: "branchId", label: "Primary Branch Ref" },
      { key: "branchIds", label: "Allowed Branch Refs", type: "tags" },
      { key: "departmentIds", label: "Allowed Department Refs", type: "tags" },
      { key: "teamIds", label: "Allowed Team Refs", type: "tags" },
      { key: "permissions", label: "Direct Permission Overrides", type: "tags" },
    ],
  },
  {
    id: "permission-catalog",
    title: "Permission Catalog",
    group: "Access Control",
    endpoint: "auth/permissions/catalog",
    description:
      "Module/action permission map used by organization admins and platform admins.",
    columns: ["Role", "Permissions"],
    rowMap: ["role", "permissions"],
    fields: [],
  },
];

export default identityModules;
