import type { CrmModule } from "../../components/crmTypes";

const identityModules: CrmModule[] = [
  {
    id: "branches",
    title: "Branches",
    group: "Security",
    endpoint: "identity/branches",
    description:
      "Organization branch offices, service desks, local settings, and operating status.",
    columns: ["Branch", "Code", "City", "Country", "Timezone", "Status"],
    rowMap: ["name", "code", "city", "country", "timezone", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Branch", required: true },
      { key: "code", label: "Code", required: true },
      { key: "city", label: "City" },
      { key: "country", label: "Country" },
      { key: "timezone", label: "Timezone" },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email", type: "email" },
      { key: "address", label: "Address" },
    ],
  },
  {
    id: "departments",
    title: "Departments",
    group: "Security",
    endpoint: "identity/departments",
    description:
      "Branch-level departments for sales, operations, finance, support, and management teams.",
    columns: ["Department", "Code", "Branch", "Manager", "Status"],
    rowMap: ["name", "code", "branchId", "managerUserId", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Department", required: true },
      { key: "code", label: "Code", required: true },
      { key: "branchId", label: "Branch", required: true },
      { key: "managerUserId", label: "Manager User ID" },
    ],
  },
  {
    id: "teams",
    title: "Teams",
    group: "Security",
    endpoint: "identity/teams",
    description:
      "Operational teams with branch, department, team lead, and member assignments.",
    columns: ["Team", "Code", "Branch", "Department", "Lead", "Status"],
    rowMap: [
      "name",
      "code",
      "branchId",
      "departmentId",
      "leadUserId",
      "status",
    ],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Team", required: true },
      { key: "code", label: "Code", required: true },
      { key: "branchId", label: "Branch", required: true },
      { key: "departmentId", label: "Department ID", required: true },
      { key: "leadUserId", label: "Lead User ID" },
      { key: "memberUserIds", label: "Member User IDs", type: "tags" },
    ],
  },
  {
    id: "roles",
    title: "Roles",
    group: "Security",
    endpoint: "identity/roles",
    description:
      "Organization roles for admins, branch managers, sales, operations, finance, agents, and custom teams.",
    columns: ["Role", "Code", "Type", "Branches", "Status"],
    rowMap: ["name", "code", "roleType", "defaultBranchIds", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Role", required: true },
      { key: "code", label: "Code", required: true },
      {
        key: "roleType",
        label: "Type",
        type: "select",
        options: [
          { value: "system", label: "System" },
          { value: "custom", label: "Custom" },
        ],
      },
      { key: "description", label: "Description" },
      { key: "defaultBranchIds", label: "Default Branch IDs", type: "tags" },
    ],
  },
  {
    id: "permissions",
    title: "Permissions",
    group: "Security",
    endpoint: "identity/permissions",
    description:
      "Action-level permission catalog used by role policies and permission overrides.",
    columns: ["Module", "Action", "Code", "Label", "Status"],
    rowMap: ["module", "action", "code", "label", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "module", label: "Module", required: true },
      { key: "action", label: "Action", required: true },
      { key: "code", label: "Code", required: true },
      { key: "label", label: "Label", required: true },
      { key: "description", label: "Description" },
    ],
  },
  {
    id: "user-roles",
    title: "User Roles",
    group: "Security",
    endpoint: "identity/user-roles",
    description:
      "User-to-role assignments with allowed branches, departments, and teams.",
    columns: ["User", "Role", "Branches", "Departments", "Teams", "Status"],
    rowMap: [
      "userId",
      "roleId",
      "branchIds",
      "departmentIds",
      "teamIds",
      "status",
    ],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "userId", label: "User ID", required: true },
      { key: "roleId", label: "Role ID", required: true },
      { key: "branchIds", label: "Branch IDs", type: "tags" },
      { key: "departmentIds", label: "Department IDs", type: "tags" },
      { key: "teamIds", label: "Team IDs", type: "tags" },
    ],
  },
  {
    id: "role-permissions",
    title: "Role Permissions",
    group: "Security",
    endpoint: "identity/role-permissions",
    description:
      "Role-to-permission grants for enterprise access policy management.",
    columns: ["Role", "Permission", "Status"],
    rowMap: ["roleId", "permissionCode", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "roleId", label: "Role ID", required: true },
      { key: "permissionCode", label: "Permission Code", required: true },
    ],
  },
  {
    id: "invitations",
    title: "Invitations",
    group: "Security",
    endpoint: "identity/invitations",
    createEndpoint: "auth/invitations",
    description:
      "Pending, accepted, expired, and revoked user invitations with branch and role context.",
    columns: ["Name", "Email", "Role", "Branch", "Expires", "Status"],
    rowMap: ["name", "email", "role", "branchId", "expiresAt", "status"],
    statusOptions: ["pending", "accepted", "expired", "revoked"],
    fields: [
      { key: "email", label: "Email", required: true, type: "email" },
      { key: "name", label: "Name", required: true },
      { key: "role", label: "Role" },
      { key: "branchId", label: "Branch" },
    ],
  },
  {
    id: "team-users",
    title: "Users & Permissions",
    group: "Security",
    endpoint: "auth/users",
    description:
      "CRM users, roles, branches, status, and fine-grained permission assignment.",
    columns: ["Name", "Email", "Role", "Branch", "Status", "Permissions"],
    rowMap: ["name", "email", "role", "branchId", "status", "permissions"],
    statusOptions: ["active", "inactive", "locked", "invited"],
    fields: [],
  },
  {
    id: "permission-catalog",
    title: "Permission Catalog",
    group: "Security",
    endpoint: "auth/permissions/catalog",
    description:
      "Module/action permission map used by organization admins and platform admins.",
    columns: ["Role", "Permissions"],
    rowMap: ["role", "permissions"],
    fields: [],
  },
];

export default identityModules;
