import type { CrmModule } from "../../components/crmTypes";

const marketingModules: CrmModule[] = [
  {
    id: "destinations",
    title: "Destinations",
    group: "Inventory",
    endpoint: "destinations",
    description:
      "Destination master with country, region, season, highlights, and visa requirement notes.",
    columns: [
      "Destination",
      "Country",
      "Region",
      "Season",
      "Highlights",
      "Status",
    ],
    rowMap: ["name", "country", "region", "bestSeason", "highlights", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Destination", required: true },
      { key: "country", label: "Country", required: true },
      { key: "region", label: "Region" },
      { key: "bestSeason", label: "Best Season" },
      { key: "highlights", label: "Highlights", type: "tags" },
      { key: "visaRequirement", label: "Visa Requirement", type: "textarea" },
    ],
  },
  {
    id: "tour-packages",
    title: "Tour Packages",
    group: "Inventory",
    endpoint: "tour-packages",
    description:
      "Reusable products and packages for B2C customers, B2B agents, campaigns, and quick quotations.",
    columns: [
      "Package",
      "Destination",
      "Category",
      "Days",
      "Base Price",
      "Status",
    ],
    rowMap: [
      "title",
      "destination",
      "category",
      "durationDays",
      "basePrice",
      "status",
    ],
    statusOptions: ["draft", "active", "inactive", "archived"],
    fields: [
      { key: "title", label: "Package", required: true },
      { key: "destination", label: "Destination", required: true },
      { key: "category", label: "Category" },
      { key: "durationDays", label: "Days", type: "number" },
      { key: "basePrice", label: "Base Price", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "inclusions", label: "Inclusions", type: "tags" },
    ],
  },
  {
    id: "travel-documents",
    title: "Travel Documents",
    group: "Operations",
    endpoint: "travel-documents",
    description:
      "Passport, visa, insurance, ticket, and customer document workflow for each booking.",
    columns: ["Customer", "Booking", "Document", "Number", "Expiry", "Status"],
    rowMap: [
      "customerName",
      "bookingId",
      "documentType",
      "documentNumber",
      "expiryDate",
      "status",
    ],
    statusOptions: ["pending", "received", "verified", "expired", "rejected"],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "documentType", label: "Document Type", required: true },
      { key: "documentNumber", label: "Document Number" },
      { key: "expiryDate", label: "Expiry", type: "date" },
      { key: "fileUrl", label: "File URL" },
    ],
  },
  {
    id: "vouchers",
    title: "Vouchers",
    group: "Operations",
    endpoint: "vouchers",
    description:
      "Hotel, transfer, activity, visa, guide, and customer vouchers issued from booking files.",
    columns: [
      "Booking",
      "Customer",
      "Type",
      "Supplier",
      "Confirmation",
      "Status",
    ],
    rowMap: [
      "bookingId",
      "customerName",
      "voucherType",
      "supplierName",
      "confirmationNumber",
      "status",
    ],
    statusOptions: ["draft", "issued", "sent", "cancelled"],
    fields: [
      { key: "bookingId", label: "Booking ID", required: true },
      { key: "customerName", label: "Customer", required: true },
      { key: "voucherType", label: "Voucher Type", required: true },
      { key: "supplierName", label: "Supplier" },
      { key: "issueDate", label: "Issue Date", type: "date" },
      { key: "confirmationNumber", label: "Confirmation No" },
    ],
  },
  {
    id: "support-tickets",
    title: "Support Tickets",
    group: "Support",
    endpoint: "support-tickets",
    description:
      "Customer, agent, supplier, and operations issue tracking with SLA-friendly statuses.",
    columns: [
      "Subject",
      "Customer",
      "Booking",
      "Channel",
      "Priority",
      "Status",
    ],
    rowMap: [
      "subject",
      "customerName",
      "bookingId",
      "channel",
      "priority",
      "status",
    ],
    statusOptions: [
      "open",
      "in_progress",
      "waiting_customer",
      "resolved",
      "closed",
    ],
    fields: [
      { key: "subject", label: "Subject", required: true },
      { key: "customerName", label: "Customer", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "channel", label: "Channel" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    group: "Control",
    endpoint: "notifications",
    description:
      "Organization and branch alerts for sales, operations, finance, support, customers, and agents.",
    columns: ["Title", "Type", "Priority", "Audience", "Module", "Status"],
    rowMap: ["title", "type", "priority", "audience", "module", "status"],
    statusOptions: ["unread", "read", "archived"],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "message", label: "Message", type: "textarea" },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: ["system", "sales", "operations", "finance", "support"],
      },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      {
        key: "audience",
        label: "Audience",
        type: "select",
        options: [
          { value: "organization", label: "Organization" },
          { value: "branch", label: "Branch" },
          { value: "user", label: "User" },
          { value: "agent", label: "Agent" },
          { value: "customer", label: "Customer" },
        ],
      },
      { key: "module", label: "Module" },
      { key: "recordId", label: "Record ID" },
      { key: "assignedTo", label: "Assigned To" },
    ],
  },
  {
    id: "campaigns",
    title: "Campaigns",
    group: "Growth",
    endpoint: "campaigns",
    description:
      "Marketing ROI tracking for lead source, campaign spend, quotations, bookings, revenue, and status.",
    columns: ["Campaign", "Channel", "Leads", "Quotes", "Bookings", "Revenue"],
    rowMap: ["name", "channel", "leads", "quotations", "bookings", "revenue"],
    statusOptions: ["draft", "active", "paused", "completed", "archived"],
    fields: [
      { key: "name", label: "Campaign", required: true },
      { key: "channel", label: "Channel", required: true },
      { key: "source", label: "Source" },
      { key: "spend", label: "Spend", type: "number" },
      { key: "leads", label: "Leads", type: "number" },
      { key: "quotations", label: "Quotes", type: "number" },
      { key: "bookings", label: "Bookings", type: "number" },
      { key: "revenue", label: "Revenue", type: "number" },
    ],
  },
];

export default marketingModules;
