import type { CrmModule } from "../../components/crmTypes";

const marketingModules: CrmModule[] = [
  {
    id: "destinations",
    title: "Destinations",
    group: "Inventory",
    endpoint: "destinations",
    description:
      "Destination master with country, region, season, highlights, and visa requirement notes.",
    columns: ["Destination", "Country", "Region", "Season", "Tier", "Status"],
    rowMap: ["name", "country", "region", "bestSeason", "popularityTier", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Destination", required: true },
      { key: "country", label: "Country", required: true },
      { key: "region", label: "Region" },
      { key: "cityCode", label: "City Code" },
      { key: "countryCode", label: "Country Code" },
      { key: "timezone", label: "Timezone" },
      { key: "bestSeason", label: "Best Season" },
      { key: "idealDuration", label: "Ideal Duration" },
      { key: "popularityTier", label: "Popularity Tier" },
      { key: "highlights", label: "Highlights", type: "tags" },
      { key: "themes", label: "Themes", type: "tags" },
      { key: "images", label: "Images", type: "tags" },
      { key: "visaRequirement", label: "Visa Requirement", type: "textarea" },
      { key: "weather", label: "Weather", type: "textarea" },
      { key: "currency", label: "Currency", type: "textarea" },
      { key: "airport", label: "Airport", type: "textarea" },
      { key: "geo", label: "Geo Details", type: "textarea" },
      { key: "content", label: "Content", type: "textarea" },
      { key: "travelAdvisory", label: "Travel Advisory", type: "textarea" },
      { key: "seo", label: "SEO", type: "textarea" },
      { key: "publishing", label: "Publishing", type: "textarea" },
      { key: "supplierCoverage", label: "Supplier Coverage", type: "textarea" },
      { key: "tags", label: "Tags", type: "tags" },
    ],
  },
  {
    id: "tour-packages",
    title: "Tour Packages",
    group: "Inventory",
    endpoint: "tour-packages",
    description:
      "Reusable products and packages for B2C customers, B2B agents, campaigns, and quick quotations.",
    columns: [
      "Code",
      "Package",
      "Destination",
      "Category",
      "Days",
      "Base Price",
      "Status",
    ],
    rowMap: [
      "packageCode",
      "title",
      "destination",
      "category",
      "durationDays",
      "basePrice",
      "status",
    ],
    statusOptions: ["draft", "active", "inactive", "archived"],
    fields: [
      { key: "title", label: "Package", required: true },
      { key: "packageCode", label: "Package Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "destinationId", label: "Destination ID" },
      { key: "supplierId", label: "Supplier ID" },
      { key: "audience", label: "Audience" },
      { key: "packageType", label: "Package Type" },
      { key: "destination", label: "Destination", required: true },
      { key: "category", label: "Category" },
      { key: "durationDays", label: "Days", type: "number" },
      { key: "durationNights", label: "Nights", type: "number" },
      { key: "minTravellers", label: "Minimum Travellers", type: "number" },
      { key: "maxTravellers", label: "Maximum Travellers", type: "number" },
      { key: "basePrice", label: "Base Price", type: "number" },
      { key: "basePriceMinor", label: "Base Price Minor", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "inclusions", label: "Inclusions", type: "tags" },
      { key: "exclusions", label: "Exclusions", type: "tags" },
      { key: "themes", label: "Themes", type: "tags" },
      { key: "images", label: "Images", type: "tags" },
      { key: "departures", label: "Departures", type: "textarea" },
      { key: "itinerary", label: "Itinerary", type: "textarea" },
      { key: "costing", label: "Costing", type: "textarea" },
      { key: "pricingRules", label: "Pricing Rules", type: "textarea" },
      { key: "commissionPolicy", label: "Commission Policy", type: "textarea" },
      { key: "bookingRules", label: "Booking Rules", type: "textarea" },
      { key: "cancellationPolicy", label: "Cancellation Policy", type: "textarea" },
      { key: "changePolicy", label: "Change Policy", type: "textarea" },
      { key: "seo", label: "SEO", type: "textarea" },
      { key: "publishing", label: "Publishing", type: "textarea" },
      { key: "publishedAt", label: "Published At", type: "date" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "customFields", label: "Custom Fields", type: "textarea" },
    ],
  },
  {
    id: "travel-documents",
    title: "Travel Documents",
    group: "Operations",
    endpoint: "travel-documents",
    description:
      "Passport, visa, insurance, ticket, and customer document workflow for each booking.",
    columns: ["Customer", "Traveller", "Booking", "Document", "Expiry", "Status"],
    rowMap: [
      "customerName",
      "travellerName",
      "bookingId",
      "documentType",
      "expiryDate",
      "status",
    ],
    statusOptions: ["pending", "received", "verified", "expired", "rejected"],
    fields: [
      { key: "customerName", label: "Customer", required: true },
      { key: "customerId", label: "Customer ID" },
      { key: "bookingId", label: "Booking ID" },
      { key: "passengerId", label: "Passenger ID" },
      { key: "travellerName", label: "Traveller Name" },
      { key: "documentType", label: "Document Type", required: true },
      { key: "documentNumber", label: "Document Number" },
      { key: "issuingCountry", label: "Issuing Country" },
      { key: "nationality", label: "Nationality" },
      { key: "issueDate", label: "Issue Date", type: "date" },
      { key: "expiryDate", label: "Expiry", type: "date" },
      { key: "fileId", label: "File ID" },
      { key: "fileUrl", label: "File URL" },
      { key: "verifiedBy", label: "Verified By" },
      { key: "requestedAt", label: "Requested At", type: "date" },
      { key: "receivedAt", label: "Received At", type: "date" },
      { key: "verifiedAt", label: "Verified At", type: "date" },
      { key: "reminderDueAt", label: "Reminder Due At", type: "date" },
      { key: "reminderStatus", label: "Reminder Status" },
      { key: "rejectionReason", label: "Rejection Reason" },
      { key: "verificationHistory", label: "Verification History", type: "textarea" },
      { key: "compliance", label: "Compliance", type: "textarea" },
      { key: "security", label: "Security", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "vouchers",
    title: "Vouchers",
    group: "Operations",
    endpoint: "vouchers",
    description:
      "Hotel, transfer, activity, visa, guide, and customer vouchers issued from booking files.",
    columns: [
      "Voucher No",
      "Booking",
      "Customer",
      "Type",
      "Supplier",
      "Confirmation",
      "Status",
    ],
    rowMap: [
      "voucherNo",
      "bookingId",
      "customerName",
      "voucherType",
      "supplierName",
      "confirmationNumber",
      "status",
    ],
    statusOptions: ["draft", "issued", "sent", "cancelled"],
    fields: [
      { key: "bookingId", label: "Booking ID", required: true },
      { key: "voucherNo", label: "Voucher No" },
      { key: "customerId", label: "Customer ID" },
      { key: "customerName", label: "Customer", required: true },
      { key: "voucherType", label: "Voucher Type", required: true },
      { key: "serviceType", label: "Service Type" },
      { key: "supplierId", label: "Supplier ID" },
      { key: "supplierName", label: "Supplier" },
      { key: "issueDate", label: "Issue Date", type: "date" },
      { key: "serviceDate", label: "Service Date", type: "date" },
      { key: "serviceTime", label: "Service Time" },
      { key: "destination", label: "Destination" },
      { key: "confirmationNumber", label: "Confirmation No" },
      { key: "fileId", label: "File ID" },
      { key: "fileUrl", label: "File URL" },
      { key: "lineItems", label: "Line Items", type: "textarea" },
      { key: "supplierConfirmation", label: "Supplier Confirmation", type: "textarea" },
      { key: "travellerInstructions", label: "Traveller Instructions", type: "textarea" },
      { key: "delivery", label: "Delivery", type: "textarea" },
      { key: "cancellationPolicy", label: "Cancellation Policy", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "support-tickets",
    title: "Support Tickets",
    group: "Support",
    endpoint: "support-tickets",
    description:
      "Customer, agent, supplier, and operations issue tracking with SLA-friendly statuses.",
    columns: [
      "Ticket No",
      "Subject",
      "Customer",
      "Booking",
      "Channel",
      "Priority",
      "Owner",
      "Status",
    ],
    rowMap: [
      "ticketNo",
      "subject",
      "customerName",
      "bookingId",
      "channel",
      "priority",
      "ownerId",
      "status",
    ],
    statusOptions: [
      "open",
      "in_progress",
      "waiting_customer",
      "resolved",
      "closed",
    ],
    fields: [
      { key: "subject", label: "Subject", required: true },
      { key: "ticketNo", label: "Ticket No" },
      { key: "customerId", label: "Customer ID" },
      { key: "customerName", label: "Customer", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "agentId", label: "Agent ID" },
      { key: "supplierId", label: "Supplier ID" },
      { key: "channel", label: "Channel" },
      { key: "source", label: "Source" },
      { key: "category", label: "Category" },
      { key: "subCategory", label: "Sub Category" },
      { key: "departmentId", label: "Department ID" },
      { key: "teamId", label: "Team ID" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "assignedTo", label: "Assigned To" },
      { key: "ownerId", label: "Owner User ID" },
      {
        key: "firstResponseDueAt",
        label: "First Response Due",
        type: "date",
      },
      { key: "firstRespondedAt", label: "First Responded At", type: "date" },
      { key: "resolutionDueAt", label: "Resolution Due", type: "date" },
      { key: "resolvedAt", label: "Resolved At", type: "date" },
      { key: "closedAt", label: "Closed At", type: "date" },
      { key: "resolutionSummary", label: "Resolution Summary", type: "textarea" },
      { key: "rootCause", label: "Root Cause", type: "textarea" },
      { key: "sla", label: "SLA", type: "textarea" },
      { key: "escalations", label: "Escalations", type: "textarea" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "messages", label: "Messages", type: "textarea" },
      { key: "tags", label: "Tags", type: "tags" },
      { key: "satisfaction", label: "Satisfaction", type: "textarea" },
      { key: "attachments", label: "Attachments", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "notifications",
    title: "Notifications",
    group: "Control",
    endpoint: "notifications",
    description:
      "Organization and branch alerts for sales, operations, finance, support, customers, and agents.",
    columns: ["Title", "Type", "Priority", "Audience", "Target", "Status"],
    rowMap: ["title", "type", "priority", "audience", "entityId", "status"],
    statusOptions: ["unread", "read", "archived"],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "message", label: "Message", type: "textarea" },
      {
        key: "type",
        label: "Type",
        type: "select",
        options: ["system", "sales", "operations", "finance", "support"],
      },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      {
        key: "audience",
        label: "Audience",
        type: "select",
        options: [
          { value: "organization", label: "Organization" },
          { value: "branch", label: "Branch" },
          { value: "user", label: "User" },
          { value: "agent", label: "Agent" },
          { value: "customer", label: "Customer" },
        ],
      },
      { key: "module", label: "Module" },
      { key: "recordId", label: "Record ID" },
      { key: "entityType", label: "Entity Type" },
      { key: "entityId", label: "Entity ID" },
      { key: "assignedTo", label: "Assigned To" },
      { key: "userId", label: "User ID" },
      { key: "agentId", label: "Agent ID" },
      { key: "customerId", label: "Customer ID" },
      { key: "actionUrl", label: "Action URL" },
      { key: "icon", label: "Icon" },
      { key: "delivery", label: "Delivery", type: "textarea" },
      { key: "scheduledAt", label: "Scheduled At", type: "date" },
      { key: "readAt", label: "Read At", type: "date" },
      { key: "archivedAt", label: "Archived At", type: "date" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "campaigns",
    title: "Campaigns",
    group: "Growth",
    endpoint: "campaigns",
    description:
      "Marketing ROI tracking for lead source, campaign spend, quotations, bookings, revenue, and status.",
    columns: ["Code", "Campaign", "Channel", "Owner", "Leads", "Revenue"],
    rowMap: ["campaignCode", "name", "channel", "ownerId", "leads", "revenue"],
    statusOptions: ["draft", "active", "paused", "completed", "archived"],
    fields: [
      { key: "name", label: "Campaign", required: true },
      { key: "campaignCode", label: "Campaign Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "channel", label: "Channel", required: true },
      { key: "source", label: "Source" },
      { key: "medium", label: "Medium" },
      { key: "campaignType", label: "Campaign Type" },
      { key: "segmentId", label: "Segment ID" },
      { key: "landingPageUrl", label: "Landing Page URL" },
      { key: "startsAt", label: "Starts At", type: "date" },
      { key: "endsAt", label: "Ends At", type: "date" },
      { key: "audience", label: "Audience", type: "textarea" },
      { key: "budget", label: "Budget", type: "textarea" },
      { key: "goals", label: "Goals", type: "textarea" },
      { key: "content", label: "Content", type: "textarea" },
      { key: "schedule", label: "Schedule", type: "textarea" },
      { key: "spend", label: "Spend", type: "number" },
      { key: "impressions", label: "Impressions", type: "number" },
      { key: "clicks", label: "Clicks", type: "number" },
      { key: "leads", label: "Leads", type: "number" },
      { key: "quotations", label: "Quotes", type: "number" },
      { key: "bookings", label: "Bookings", type: "number" },
      { key: "revenue", label: "Revenue", type: "number" },
      { key: "costPerLead", label: "Cost Per Lead", type: "number" },
      { key: "roi", label: "ROI", type: "number" },
      { key: "attribution", label: "Attribution", type: "textarea" },
      { key: "provider", label: "Provider", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
];

export default marketingModules;
