import type { CrmModule } from "../../components/crmTypes";

const operationsModules: CrmModule[] = [
  {
    id: "tasks",
    title: "Tasks",
    group: "Operations",
    endpoint: "tasks",
    description:
      "Cross-module tasks and follow-ups for sales, bookings, suppliers, support, finance, and operations teams.",
    columns: ["Task", "Module", "Entity", "Owner", "Due", "Priority", "Status"],
    rowMap: [
      "title",
      "module",
      "entityId",
      "assignedTo",
      "dueAt",
      "priority",
      "status",
    ],
    statusOptions: ["open", "in_progress", "waiting", "completed", "cancelled"],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "module", label: "Module" },
      { key: "entityId", label: "Record ID" },
      { key: "assignedTo", label: "Owner" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "dueAt", label: "Due Date", type: "date" },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    group: "Operations",
    endpoint: "operations",
    description:
      "DMC execution tasks for hotels, transfers, visas, tickets, guides, confirmations, and supplier follow-ups.",
    columns: ["Task", "Booking", "Service", "Owner", "Due", "Status"],
    rowMap: [
      "title",
      "bookingId",
      "serviceType",
      "assignedTo",
      "dueAt",
      "status",
    ],
    statusOptions: [
      "pending",
      "assigned",
      "confirmed",
      "in_progress",
      "blocked",
      "completed",
    ],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "serviceType", label: "Service", required: true },
      { key: "assignedTo", label: "Owner" },
      { key: "dueAt", label: "Due Date", type: "date" },
      {
        key: "payload.priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
    ],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    group: "Inventory",
    endpoint: "suppliers",
    description:
      "Hotels, transporters, activity vendors, guides, DMC partners, contracts, credit limits, ratings, and payables.",
    columns: [
      "Supplier",
      "Type",
      "Destination",
      "Credit Limit",
      "Rating",
      "Status",
    ],
    rowMap: ["name", "type", "destination", "creditLimit", "rating", "status"],
    statusOptions: ["active", "inactive", "blacklisted"],
    fields: [
      { key: "name", label: "Supplier", required: true },
      { key: "type", label: "Type", required: true },
      { key: "destination", label: "Destination" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "rating", label: "Rating", type: "number" },
    ],
  },
  {
    id: "b2b-agents",
    title: "B2B Agents",
    group: "Partners",
    endpoint: "b2b-agents",
    description:
      "Agent onboarding, KYC status, market, credit limit, commission, receivables, and partner activity.",
    columns: [
      "Agency",
      "Contact",
      "Market",
      "Credit Limit",
      "Commission",
      "Status",
    ],
    rowMap: [
      "agencyName",
      "contactName",
      "market",
      "creditLimit",
      "commissionRate",
      "status",
    ],
    statusOptions: ["pending_kyc", "active", "on_hold", "blocked"],
    fields: [
      { key: "agencyName", label: "Agency", required: true },
      { key: "contactName", label: "Contact", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "market", label: "Market" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "commissionRate", label: "Commission %", type: "number" },
    ],
  },
  {
    id: "tags",
    title: "Tags",
    group: "Inventory",
    endpoint: "tags",
    description:
      "Reusable organization taxonomy for labeling leads, customers, bookings, suppliers, support, and campaigns.",
    columns: ["Tag", "Module", "Color", "Description", "Status"],
    rowMap: ["name", "module", "color", "description", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Tag", required: true },
      { key: "module", label: "Module" },
      { key: "color", label: "Color" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
];

export default operationsModules;
