import type { CrmModule } from "../../components/crmTypes";

const metadataFields = [
  { key: "tags", label: "Tags", type: "tags" as const },
  { key: "customFields", label: "Custom Fields", type: "textarea" as const },
  { key: "metadata", label: "Internal Metadata", type: "textarea" as const },
];

const operationsModules: CrmModule[] = [
  {
    id: "tasks",
    title: "Tasks",
    group: "Operations",
    endpoint: "tasks",
    description:
      "Cross-module tasks and follow-ups for sales, bookings, suppliers, support, finance, and operations teams.",
    columns: ["Task", "Module", "Entity", "Owner", "Due", "Priority", "Status"],
    rowMap: [
      "title",
      "module",
      "entityId",
      "assignedTo",
      "dueAt",
      "priority",
      "status",
    ],
    statusOptions: ["open", "in_progress", "waiting", "completed", "cancelled"],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "module", label: "Module" },
      { key: "entityType", label: "Entity Type" },
      { key: "entityId", label: "Record ID" },
      { key: "assignedTo", label: "Owner" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "departmentId", label: "Department ID" },
      { key: "teamId", label: "Team ID" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "dueAt", label: "Due Date", type: "date" },
      { key: "startedAt", label: "Started At", type: "date" },
      { key: "completedAt", label: "Completed At", type: "date" },
      { key: "checklist", label: "Checklist", type: "textarea" },
      { key: "comments", label: "Comments", type: "textarea" },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    group: "Operations",
    endpoint: "operations",
    description:
      "DMC execution tasks for hotels, transfers, visas, tickets, guides, confirmations, and supplier follow-ups.",
    columns: [
      "Task",
      "Booking",
      "Service",
      "Owner",
      "Team",
      "Due",
      "SLA",
      "Status",
    ],
    rowMap: [
      "title",
      "bookingId",
      "serviceType",
      "ownerId",
      "teamId",
      "dueAt",
      "slaStatus",
      "status",
    ],
    statusOptions: [
      "pending",
      "assigned",
      "confirmed",
      "in_progress",
      "issue",
      "completed",
    ],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "customerId", label: "Customer ID" },
      { key: "supplierId", label: "Supplier ID" },
      { key: "voucherId", label: "Voucher ID" },
      { key: "departmentId", label: "Department ID" },
      { key: "serviceType", label: "Service", required: true },
      { key: "assignedTo", label: "Owner" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "teamId", label: "Team ID" },
      { key: "dueAt", label: "Due Date", type: "date" },
      { key: "startedAt", label: "Started At", type: "date" },
      { key: "completedAt", label: "Completed At", type: "date" },
      { key: "confirmedAt", label: "Confirmed At", type: "date" },
      { key: "location", label: "Location" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "slaStatus", label: "SLA Status" },
      { key: "qualityCheck", label: "Quality Check", type: "textarea" },
      {
        key: "supplierConfirmation",
        label: "Supplier Confirmation",
        type: "textarea",
      },
      { key: "checklist", label: "Checklist", type: "textarea" },
      { key: "fieldUpdate", label: "Field Update", type: "textarea" },
      { key: "timeline", label: "Timeline", type: "textarea" },
      { key: "escalations", label: "Escalations", type: "textarea" },
      { key: "dependencies", label: "Dependencies", type: "textarea" },
      ...metadataFields,
    ],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    group: "Inventory",
    endpoint: "suppliers",
    description:
      "Hotels, transporters, activity vendors, guides, DMC partners, contracts, credit limits, ratings, and payables.",
    columns: [
      "Code",
      "Supplier",
      "Type",
      "Destination",
      "Credit Limit",
      "Owner",
      "Status",
    ],
    rowMap: [
      "supplierCode",
      "name",
      "type",
      "destination",
      "creditLimit",
      "ownerId",
      "status",
    ],
    statusOptions: ["active", "inactive", "blocked"],
    fields: [
      { key: "name", label: "Supplier", required: true },
      { key: "supplierCode", label: "Supplier Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "legalName", label: "Legal Name" },
      { key: "market", label: "Market" },
      { key: "preferredCurrency", label: "Preferred Currency" },
      { key: "accountManagerId", label: "Account Manager ID" },
      { key: "type", label: "Type", required: true },
      { key: "destination", label: "Destination" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "payable", label: "Payable", type: "number" },
      { key: "rating", label: "Rating", type: "number" },
      { key: "contacts", label: "Contacts", type: "textarea" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "contracts", label: "Contracts", type: "textarea" },
      { key: "rates", label: "Rates", type: "textarea" },
      { key: "confirmations", label: "Confirmations", type: "textarea" },
      { key: "taxProfile", label: "Tax Profile", type: "textarea" },
      { key: "bankDetails", label: "Bank Details", type: "textarea" },
      { key: "paymentTerms", label: "Payment Terms", type: "textarea" },
      { key: "compliance", label: "Compliance", type: "textarea" },
      { key: "performance", label: "Performance", type: "textarea" },
      { key: "serviceCoverage", label: "Service Coverage", type: "textarea" },
      { key: "documents", label: "Documents", type: "textarea" },
      ...metadataFields,
    ],
  },
  {
    id: "b2b-agents",
    title: "B2B Agents",
    group: "Partners",
    endpoint: "b2b-agents",
    description:
      "Agent onboarding, KYC status, market, credit limit, commission, receivables, and partner activity.",
    columns: [
      "Agent Code",
      "Agency",
      "Contact",
      "Market",
      "Credit Limit",
      "Owner",
      "Status",
    ],
    rowMap: [
      "agentCode",
      "agencyName",
      "contactName",
      "market",
      "creditLimit",
      "ownerId",
      "status",
    ],
    statusOptions: ["pending_kyc", "active", "suspended", "blocked"],
    fields: [
      { key: "agencyName", label: "Agency", required: true },
      { key: "agentCode", label: "Agent Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "contactName", label: "Contact", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "market", label: "Market" },
      { key: "agentType", label: "Agent Type" },
      { key: "territory", label: "Territory" },
      { key: "preferredCurrency", label: "Preferred Currency" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "availableCredit", label: "Available Credit", type: "number" },
      { key: "receivable", label: "Receivable", type: "number" },
      { key: "commissionEarned", label: "Commission Earned", type: "number" },
      { key: "walletBalance", label: "Wallet Balance", type: "number" },
      { key: "kycDocuments", label: "KYC Documents", type: "textarea" },
      { key: "taxProfile", label: "Tax Profile", type: "textarea" },
      { key: "bankDetails", label: "Bank Details", type: "textarea" },
      { key: "contractTerms", label: "Contract Terms", type: "textarea" },
      { key: "creditPolicy", label: "Credit Policy", type: "textarea" },
      { key: "pricingPolicy", label: "Pricing Policy", type: "textarea" },
      { key: "portalAccess", label: "Portal Access", type: "textarea" },
      { key: "performance", label: "Performance", type: "textarea" },
      { key: "onboardedAt", label: "Onboarded At", type: "date" },
      { key: "lastBookingAt", label: "Last Booking At", type: "date" },
      ...metadataFields,
    ],
  },
  {
    id: "tags",
    title: "Tags",
    group: "Inventory",
    endpoint: "tags",
    description:
      "Reusable organization taxonomy for labeling leads, customers, bookings, suppliers, support, and campaigns.",
    columns: ["Tag", "Module", "Color", "Description", "Status"],
    rowMap: ["name", "module", "color", "description", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Tag", required: true },
      { key: "module", label: "Module" },
      { key: "entityType", label: "Entity Type" },
      { key: "usageCount", label: "Usage Count", type: "number" },
      { key: "color", label: "Color" },
      { key: "rules", label: "Rules", type: "textarea" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
];

export default operationsModules;
