import type { CrmModule } from "../../components/crmTypes";

const metadataFields = [
  { key: "tags", label: "Tags", type: "tags" as const },
  { key: "customFields", label: "Custom Fields", type: "textarea" as const },
  { key: "metadata", label: "Internal Metadata", type: "textarea" as const },
];

const operationsModules: CrmModule[] = [
  {
    id: "tasks",
    title: "Tasks",
    group: "Operations",
    endpoint: "tasks",
    description:
      "Cross-module tasks and follow-ups for sales, bookings, suppliers, support, finance, and operations teams.",
    columns: ["Task", "Module", "Entity", "Owner", "Due", "Priority", "Status"],
    rowMap: [
      "title",
      "module",
      "entityId",
      "assignedTo",
      "dueAt",
      "priority",
      "status",
    ],
    statusOptions: ["open", "in_progress", "waiting", "completed", "cancelled"],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "module", label: "Module" },
      { key: "entityId", label: "Record ID" },
      { key: "assignedTo", label: "Owner" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "dueAt", label: "Due Date", type: "date" },
    ],
  },
  {
    id: "operations",
    title: "Operations",
    group: "Operations",
    endpoint: "operations",
    description:
      "DMC execution tasks for hotels, transfers, visas, tickets, guides, confirmations, and supplier follow-ups.",
    columns: ["Task", "Booking", "Service", "Owner", "Team", "Due", "SLA", "Status"],
    rowMap: [
      "title",
      "bookingId",
      "serviceType",
      "ownerId",
      "teamId",
      "dueAt",
      "slaStatus",
      "status",
    ],
    statusOptions: [
      "pending",
      "assigned",
      "confirmed",
      "in_progress",
      "issue",
      "completed",
    ],
    fields: [
      { key: "title", label: "Task", required: true },
      { key: "bookingId", label: "Booking ID" },
      { key: "customerId", label: "Customer ID" },
      { key: "serviceType", label: "Service", required: true },
      { key: "assignedTo", label: "Owner" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "teamId", label: "Team ID" },
      { key: "dueAt", label: "Due Date", type: "date" },
      { key: "startedAt", label: "Started At", type: "date" },
      { key: "completedAt", label: "Completed At", type: "date" },
      {
        key: "priority",
        label: "Priority",
        type: "select",
        options: ["low", "medium", "high", "urgent"],
      },
      { key: "slaStatus", label: "SLA Status" },
      { key: "qualityCheck", label: "Quality Check", type: "textarea" },
      { key: "supplierConfirmation", label: "Supplier Confirmation", type: "textarea" },
      ...metadataFields,
    ],
  },
  {
    id: "suppliers",
    title: "Suppliers",
    group: "Inventory",
    endpoint: "suppliers",
    description:
      "Hotels, transporters, activity vendors, guides, DMC partners, contracts, credit limits, ratings, and payables.",
    columns: [
      "Code",
      "Supplier",
      "Type",
      "Destination",
      "Credit Limit",
      "Owner",
      "Status",
    ],
    rowMap: ["supplierCode", "name", "type", "destination", "creditLimit", "ownerId", "status"],
    statusOptions: ["active", "inactive", "blocked"],
    fields: [
      { key: "name", label: "Supplier", required: true },
      { key: "supplierCode", label: "Supplier Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "type", label: "Type", required: true },
      { key: "destination", label: "Destination" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "rating", label: "Rating", type: "number" },
      { key: "contacts", label: "Contacts", type: "textarea" },
      { key: "taxProfile", label: "Tax Profile", type: "textarea" },
      { key: "bankDetails", label: "Bank Details", type: "textarea" },
      { key: "paymentTerms", label: "Payment Terms", type: "textarea" },
      { key: "compliance", label: "Compliance", type: "textarea" },
      ...metadataFields,
    ],
  },
  {
    id: "b2b-agents",
    title: "B2B Agents",
    group: "Partners",
    endpoint: "b2b-agents",
    description:
      "Agent onboarding, KYC status, market, credit limit, commission, receivables, and partner activity.",
    columns: [
      "Agent Code",
      "Agency",
      "Contact",
      "Market",
      "Credit Limit",
      "Owner",
      "Status",
    ],
    rowMap: [
      "agentCode",
      "agencyName",
      "contactName",
      "market",
      "creditLimit",
      "ownerId",
      "status",
    ],
    statusOptions: ["pending_kyc", "active", "suspended", "blocked"],
    fields: [
      { key: "agencyName", label: "Agency", required: true },
      { key: "agentCode", label: "Agent Code" },
      { key: "ownerId", label: "Owner User ID" },
      { key: "contactName", label: "Contact", required: true },
      { key: "email", label: "Email", type: "email" },
      { key: "phone", label: "Phone" },
      { key: "market", label: "Market" },
      { key: "creditLimit", label: "Credit Limit", type: "number" },
      { key: "taxProfile", label: "Tax Profile", type: "textarea" },
      { key: "bankDetails", label: "Bank Details", type: "textarea" },
      { key: "contractTerms", label: "Contract Terms", type: "textarea" },
      { key: "creditPolicy", label: "Credit Policy", type: "textarea" },
      ...metadataFields,
    ],
  },
  {
    id: "tags",
    title: "Tags",
    group: "Inventory",
    endpoint: "tags",
    description:
      "Reusable organization taxonomy for labeling leads, customers, bookings, suppliers, support, and campaigns.",
    columns: ["Tag", "Module", "Color", "Description", "Status"],
    rowMap: ["name", "module", "color", "description", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "name", label: "Tag", required: true },
      { key: "module", label: "Module" },
      { key: "color", label: "Color" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },
];

export default operationsModules;
