import type { CrmModule } from "../../components/crmTypes";

const platformModules: CrmModule[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    group: "Overview",
    description:
      "Live operating view across sales, bookings, operations, partners, suppliers, documents, support, and finance.",
    columns: ["Signal", "Value", "Owner", "Status"],
    rowMap: [],
    fields: [],
  },
  {
    id: "my-profile",
    title: "My Profile",
    group: "Account",
    description:
      "Personal CRM profile, contact preferences, locale, timezone, and notification settings.",
    columns: [],
    rowMap: [],
    fields: [],
  },
  {
    id: "change-password",
    title: "Change Password",
    group: "Account",
    description:
      "Update your CRM password and keep the current session active while older sessions are revoked.",
    columns: [],
    rowMap: [],
    fields: [],
  },
  {
    id: "subscription-plans",
    title: "Subscription Plans",
    group: "Account",
    endpoint: "plans",
    createEndpoint: "subscriptions",
    description:
      "Available TripOS CRM plans for travel companies, B2B agent operations, B2C mobile add-ons, and enterprise support.",
    columns: ["Plan", "Audience", "Cycle", "Price", "Seats", "Status"],
    rowMap: [
      "name",
      "audience",
      "billingCycle",
      "priceMinor",
      "includedSeats",
      "status",
    ],
    fields: [
      { key: "planCode", label: "Plan Code", required: true },
      { key: "seats", label: "Seats", type: "number" },
      { key: "billingProfile", label: "Billing Profile", type: "textarea" },
    ],
  },
  {
    id: "pricing-plans",
    title: "Pricing Plans",
    group: "System",
    endpoint: "plans",
    description:
      "TripOS sellable SaaS plans for travel companies, B2B agent portals, implementation, seats, and support tiers.",
    columns: ["Plan", "Audience", "Cycle", "Price", "Seats", "Status"],
    rowMap: [
      "name",
      "audience",
      "billingCycle",
      "priceMinor",
      "includedSeats",
      "status",
    ],
    statusOptions: ["active", "inactive", "archived"],
    fields: [
      { key: "code", label: "Plan Code", required: true },
      { key: "name", label: "Plan Name", required: true },
      { key: "description", label: "Description", type: "textarea" },
      {
        key: "audience",
        label: "Audience",
        type: "select",
        options: [
          { value: "b2b_crm", label: "Travel Company CRM" },
          { value: "agent_portal", label: "B2B Agent Portal" },
          { value: "b2c_mobile", label: "B2C Mobile Add-on" },
          { value: "enterprise", label: "Enterprise Suite" },
        ],
      },
      {
        key: "billingCycle",
        label: "Billing Cycle",
        type: "select",
        options: [
          { value: "monthly", label: "Monthly" },
          { value: "quarterly", label: "Quarterly" },
          { value: "half_yearly", label: "Half Yearly" },
          { value: "yearly", label: "Yearly" },
        ],
      },
      { key: "currencyCode", label: "Currency Code" },
      { key: "priceMinor", label: "Price Minor", type: "number" },
      { key: "setupFeeMinor", label: "Setup Fee Minor", type: "number" },
      { key: "trialDays", label: "Trial Days", type: "number" },
      { key: "minSeats", label: "Minimum Seats", type: "number" },
      { key: "includedSeats", label: "Included Seats", type: "number" },
      {
        key: "extraSeatPriceMinor",
        label: "Extra Seat Price Minor",
        type: "number",
      },
      { key: "features", label: "Features", type: "tags" },
      { key: "limits", label: "Limits", type: "textarea" },
      { key: "providerPrices", label: "Provider Prices", type: "textarea" },
      { key: "terms", label: "Terms", type: "textarea" },
      { key: "tags", label: "Tags", type: "tags" },
    ],
  },
  {
    id: "subscriptions",
    title: "Subscriptions",
    group: "System",
    endpoint: "subscriptions",
    description:
      "Organization subscription lifecycle, seats, billing profile, renewal state, and sandbox/live provider references.",
    columns: ["Plan", "Cycle", "Seats", "Amount", "Provider", "Status"],
    rowMap: [
      "planName",
      "billingCycle",
      "seats",
      "amountMinor",
      "paymentProvider",
      "status",
    ],
    statusOptions: ["pending", "trialing", "active", "past_due", "cancelled"],
    fields: [
      { key: "planCode", label: "Plan Code", required: true },
      { key: "seats", label: "Seats", type: "number" },
      { key: "paymentProvider", label: "Payment Provider" },
      { key: "providerCustomerId", label: "Provider Customer ID" },
      { key: "providerSubscriptionId", label: "Provider Subscription ID" },
      { key: "billingProfile", label: "Billing Profile", type: "textarea" },
      { key: "metadata", label: "Metadata", type: "textarea" },
    ],
  },
  {
    id: "organizations",
    title: "Organizations",
    group: "System",
    endpoint: "organizations",
    description:
      "SaaS organization profiles with billing, subscription, branding, data hosting, security, and integration settings.",
    columns: ["Organization", "Code", "Type", "Hosting", "Currency", "Status"],
    rowMap: ["name", "code", "organizationType", "dataHostingMode", "baseCurrency", "status"],
    statusOptions: ["active", "inactive", "suspended"],
    fields: [
      { key: "name", label: "Organization", required: true },
      { key: "code", label: "Code", required: true },
      { key: "legalName", label: "Legal Name" },
      { key: "organizationType", label: "Organization Type" },
      { key: "industry", label: "Industry" },
      { key: "website", label: "Website" },
      { key: "primaryEmail", label: "Primary Email", type: "email" },
      { key: "primaryPhone", label: "Primary Phone" },
      { key: "timezone", label: "Timezone" },
      { key: "locale", label: "Locale" },
      { key: "baseCurrency", label: "Base Currency" },
      {
        key: "dataHostingMode",
        label: "Data Hosting",
        type: "select",
        options: [
          { value: "tripos_cloud", label: "TripOS Cloud" },
          { value: "customer_managed", label: "Customer Managed" },
          { value: "hybrid_sync", label: "Hybrid Sync" },
        ],
      },
      { key: "branches", label: "Branches", type: "textarea" },
      { key: "syncPolicy", label: "Sync Policy", type: "textarea" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "contacts", label: "Contacts", type: "textarea" },
      { key: "billingProfile", label: "Billing Profile", type: "textarea" },
      { key: "subscription", label: "Subscription", type: "textarea" },
      { key: "commercial", label: "Commercial", type: "textarea" },
      { key: "branding", label: "Branding", type: "textarea" },
      { key: "compliance", label: "Compliance", type: "textarea" },
      { key: "securityPolicy", label: "Security Policy", type: "textarea" },
      { key: "integrations", label: "Integrations", type: "textarea" },
      { key: "notificationPolicy", label: "Notification Policy", type: "textarea" },
      { key: "retentionPolicy", label: "Retention Policy", type: "textarea" },
      { key: "auditPolicy", label: "Audit Policy", type: "textarea" },
      { key: "onboardedAt", label: "Onboarded At", type: "date" },
      { key: "trialEndsAt", label: "Trial Ends At", type: "date" },
      { key: "suspendedAt", label: "Suspended At", type: "date" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "audit-logs",
    title: "Audit Logs",
    group: "Security",
    endpoint: "audit-logs",
    description:
      "Organization-scoped audit trail for protected mutations and sensitive reads with export-ready payloads.",
    columns: [
      "Action",
      "Entity",
      "Actor",
      "Method",
      "Path",
      "Outcome",
      "Status",
    ],
    rowMap: [
      "action",
      "entityType",
      "actorRole",
      "method",
      "path",
      "outcome",
      "statusCode",
    ],
    fields: [],
  },
  {
    id: "storage-files",
    title: "Storage Files",
    group: "System",
    endpoint: "storage/files",
    createEndpoint: "storage/files/upload-intent",
    description:
      "Registry for passports, vouchers, tickets, contracts, receipts, and generated PDFs.",
    columns: ["Entity", "File", "MIME", "Size", "Visibility", "Status"],
    rowMap: [
      "entityType",
      "fileName",
      "mimeType",
      "size",
      "visibility",
      "status",
    ],
    fields: [
      { key: "entityType", label: "Entity Type", required: true },
      { key: "entityId", label: "Entity ID", required: true },
      { key: "fileName", label: "File Name", required: true },
      { key: "mimeType", label: "MIME Type", required: true },
      { key: "size", label: "Size", required: true, type: "number" },
      { key: "checksum", label: "Checksum" },
      { key: "uploadedBy", label: "Uploaded By" },
      { key: "visibility", label: "Visibility" },
      { key: "retention", label: "Retention", type: "textarea" },
      { key: "scanResult", label: "Scan Result", type: "textarea" },
      { key: "metadata", label: "Metadata", type: "textarea" },
    ],
  },
  {
    id: "integrations",
    title: "Integrations",
    group: "System",
    endpoint: "integrations/health",
    description:
      "Local/log health status for email, WhatsApp, SMS, payments, maps, AI, monitoring, and storage.",
    columns: ["Provider", "Enabled", "Mode"],
    rowMap: ["provider", "enabled", "mode"],
    fields: [],
  },
  {
    id: "settings",
    title: "Settings",
    group: "System",
    endpoint: "settings",
    description:
      "Organization and branch runtime settings for branding, defaults, workflow controls, and integrations.",
    columns: ["Key", "Label", "Category", "Status"],
    rowMap: ["key", "label", "category", "status"],
    statusOptions: ["active", "inactive"],
    fields: [
      { key: "key", label: "Key", required: true },
      { key: "label", label: "Label", required: true },
      { key: "category", label: "Category" },
      { key: "value", label: "Value", type: "textarea" },
    ],
  },
  {
    id: "feature-flags",
    title: "Feature Flags",
    group: "System",
    endpoint: "feature-flags",
    description:
      "Organization and branch feature controls for TripOS CRM, B2B agent flows, B2C mobile features, and rollout rules.",
    columns: ["Flag", "Label", "Category", "Enabled", "Status"],
    rowMap: ["key", "label", "category", "enabled", "status"],
    statusOptions: ["active", "inactive", "archived"],
    fields: [
      { key: "key", label: "Flag Key", required: true },
      { key: "label", label: "Label", required: true },
      { key: "category", label: "Category" },
      { key: "enabled", label: "Enabled", type: "select", options: [
        { value: "true", label: "Enabled" },
        { value: "false", label: "Disabled" },
      ] },
      { key: "rollout", label: "Rollout", type: "textarea" },
      { key: "rules", label: "Rules", type: "textarea" },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "workflows",
    title: "Workflows",
    group: "System",
    endpoint: "workflows",
    description:
      "Travel automation rules for lead follow-up, quotation expiry, booking handoff, supplier SLA, document reminders, and payment alerts.",
    columns: ["Workflow", "Code", "Module", "Trigger", "Priority", "Status"],
    rowMap: ["name", "code", "module", "trigger", "priority", "status"],
    statusOptions: ["active", "inactive", "paused"],
    fields: [
      { key: "name", label: "Workflow", required: true },
      { key: "code", label: "Code", required: true },
      { key: "module", label: "Module" },
      { key: "trigger", label: "Trigger" },
      { key: "conditions", label: "Conditions", type: "textarea" },
      { key: "actions", label: "Actions", type: "textarea" },
      { key: "priority", label: "Priority", type: "number" },
      { key: "runOnce", label: "Run Once", type: "select", options: [
        { value: "true", label: "Yes" },
        { value: "false", label: "No" },
      ] },
      { key: "metadata", label: "Internal Metadata", type: "textarea" },
    ],
  },
  {
    id: "communications",
    title: "Communications",
    group: "System",
    endpoint: "communications",
    description:
      "Email, SMS, WhatsApp, push, and call communication records for leads, customers, agents, bookings, vouchers, and payments.",
    columns: ["Channel", "Recipient", "Subject", "Template", "Provider", "Status"],
    rowMap: ["channel", "recipient", "subject", "templateCode", "provider", "status"],
    statusOptions: ["draft", "queued", "sent", "delivered", "failed", "cancelled"],
    fields: [
      { key: "channel", label: "Channel", type: "select", options: ["email", "sms", "whatsapp", "push", "call"] },
      { key: "category", label: "Category" },
      { key: "entityType", label: "Entity Type" },
      { key: "entityId", label: "Entity ID" },
      { key: "recipient", label: "Recipient", required: true },
      { key: "recipientName", label: "Recipient Name" },
      { key: "subject", label: "Subject" },
      { key: "templateCode", label: "Template Code" },
      { key: "provider", label: "Provider" },
      { key: "providerMessageId", label: "Provider Message ID" },
      { key: "payload", label: "Payload", type: "textarea" },
      { key: "metadata", label: "Metadata", type: "textarea" },
      { key: "scheduledAt", label: "Scheduled At", type: "date" },
    ],
  },
  {
    id: "imports-exports",
    title: "Imports & Exports",
    group: "System",
    endpoint: "imports-exports",
    description:
      "Operational audit of bulk imports, exports, generated files, row counts, failures, and requested-by context.",
    columns: ["Type", "Module", "File", "Format", "Rows", "Status"],
    rowMap: ["jobType", "module", "fileName", "format", "totalRows", "status"],
    statusOptions: ["queued", "running", "completed", "failed", "cancelled"],
    fields: [
      { key: "jobType", label: "Job Type", type: "select", options: ["import", "export"] },
      { key: "module", label: "Module", required: true },
      { key: "fileName", label: "File Name" },
      { key: "format", label: "Format" },
      { key: "totalRows", label: "Total Rows", type: "number" },
      { key: "successRows", label: "Success Rows", type: "number" },
      { key: "failedRows", label: "Failed Rows", type: "number" },
      { key: "requestedBy", label: "Requested By" },
      { key: "metadata", label: "Metadata", type: "textarea" },
    ],
  },
  {
    id: "batch-jobs",
    title: "Batch Jobs",
    group: "System",
    endpoint: "batch-jobs",
    description:
      "Scheduled platform jobs for notification retention, operations SLA checks, and manual sandbox runs.",
    columns: ["Job", "Interval", "Last Status", "Last Run", "Result"],
    rowMap: [
      "name",
      "intervalMinutes",
      "lastStatus",
      "lastRunAt",
      "lastResult",
    ],
    fields: [],
  },
];

export default platformModules;
