export const COLLECTION_NAMES = {
  LEAD: 'tripos_leads',
  LEAD_ACTIVITY: 'tripos_lead_activities',
  INVOICE: 'tripos_invoices',
  MODULE_RECORD: 'tripos_records',
  QUOTATION: 'tripos_quotations',
  ITINERARY: 'tripos_itineraries',
  BOOKING: 'tripos_bookings',
  SUPPLIER: 'tripos_suppliers',
  OPERATION_TASK: 'tripos_operation_tasks',
  B2B_AGENT: 'tripos_b2b_agents',
  PAYMENT: 'tripos_payments',
  CUSTOMER: 'tripos_customers',
  DESTINATION: 'tripos_destinations',
  TOUR_PACKAGE: 'tripos_tour_packages',
  TRAVEL_DOCUMENT: 'tripos_travel_documents',
  VOUCHER: 'tripos_vouchers',
  SUPPORT_TICKET: 'tripos_support_tickets',
  CAMPAIGN: 'tripos_campaigns',
  TENANT: 'tripos_tenants',
  CRM_USER: 'tripos_crm_users',
  USER_SESSION: 'tripos_user_sessions',
  AUDIT_LOG: 'tripos_audit_logs',
} as const;
