export const COLLECTION_NAMES = {
  LEAD: 'leads',
  LEAD_ACTIVITY: 'lead_activities',
  INVOICE: 'invoices',
  QUOTATION: 'quotations',
  ITINERARY: 'itineraries',
  BOOKING: 'bookings',
  SUPPLIER: 'suppliers',
  OPERATION_TASK: 'operation_tasks',
  B2B_AGENT: 'b2b_agents',
  PAYMENT: 'payments',
  CUSTOMER: 'customers',
  DESTINATION: 'destinations',
  TOUR_PACKAGE: 'tour_packages',
  TRAVEL_DOCUMENT: 'travel_documents',
  VOUCHER: 'vouchers',
  SUPPORT_TICKET: 'support_tickets',
  CAMPAIGN: 'campaigns',
  TENANT: 'tenants',
  CRM_USER: 'crm_users',
  USER_SESSION: 'user_sessions',
  AUDIT_LOG: 'audit_logs',
  STORED_FILE: 'stored_files',
  SAVED_REPORT: 'saved_reports',
} as const;
